<a href="https://colab.research.google.com/github/GV2410/DWP-TECH-LAB/blob/main/DWP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

numbers = [1, 2, 3, 4, 5,60]  # Create a list of numbers
mean_value = np.mean(numbers)  # Calculate the mean using numpy's mean function
print(mean_value) # Print the result
np.median(numbers)

12.5

3.5

In [ ]:
# prompt: complete case analysis with definition and example

import pandas as pd
import numpy as np

# Definition:
# Complete case analysis (CCA), also known as listwise deletion, is a method for handling missing data in a dataset.
# It involves removing any data points that have missing values in any of the variables of interest.
# The analysis is then conducted only on the remaining complete cases.

# Example:

# Sample DataFrame with missing values
data = {'col1': [1, 2, np.nan, 4, 5],
        'col2': [6, 7, 8, np.nan, 10],
        'col3': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Perform complete case analysis
df_cca = df.dropna()
print(df.isna().sum())

print("\nDataFrame after Complete Case Analysis:")
df_cca
# Explanation:
# The original DataFrame has missing values (NaN) in 'col1' and 'col2'.
# The dropna() function removes any row with at least one NaN value.
# The resulting df_cca contains only complete cases, excluding rows with missing data.

Original DataFrame:
   col1  col2  col3
0   1.0   6.0    11
1   2.0   7.0    12
2   NaN   8.0    13
3   4.0   NaN    14
4   5.0  10.0    15
col1    1
col2    1
col3    0
dtype: int64

DataFrame after Complete Case Analysis:

   col1  col2  col3
0   1.0   6.0    11
1   2.0   7.0    12
4   5.0  10.0    15

In [ ]:
# prompt: Handling missing numerical data
# a) mean or median imputation with definition and get  age and gender dataset and when to use mean and median imputation

import pandas as pd
import numpy as np

# Sample DataFrame with missing age and gender data
data = {'age': [25, 30, np.nan, 40, 35, np.nan, 28, 22, np.nan, 45],
        'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', np.nan]}
df = pd.DataFrame(data)

# Mean imputation for age
mean_age = df['age'].mean()
df['age_mean_imputed'] = df['age'].fillna(mean_age)

# Median imputation for age
median_age = df['age'].median()
df['age_median_imputed'] = df['age'].fillna(median_age)


# Mode imputation for gender (categorical data)
mode_gender = df['gender'].mode()[0] # mode() returns a Series, we take the first element
df['gender_mode_imputed'] = df['gender'].fillna(mode_gender)


print("Original DataFrame:\n", df)
print("\nDataFrame with mean/median/mode imputation:\n", df[['age', 'age_mean_imputed', 'age_median_imputed', 'gender', 'gender_mode_imputed']])


# When to use mean vs. median imputation:
# Mean imputation is generally preferred when the data is normally distributed and does not have significant outliers.
# Median imputation is preferred when the data is skewed or has outliers, as the median is less sensitive to extreme values.

# Example illustrating the difference:
# Create a dataset with an outlier
data_outlier = {'age': [25, 30, 32, 35, 38, 150]}  # 150 is an outlier
df_outlier = pd.DataFrame(data_outlier)
mean_age_outlier = df_outlier['age'].mean()
median_age_outlier = df_outlier['age'].median()
print(f"\nExample with outlier:")
print(f"Mean age with outlier: {mean_age_outlier}")
print(f"Median age with outlier: {median_age_outlier}")

Original DataFrame:
     age  gender  age_mean_imputed  age_median_imputed gender_mode_imputed
0  25.0    Male         25.000000                25.0                Male
1  30.0  Female         30.000000                30.0              Female
2   NaN    Male         32.142857                30.0                Male
3  40.0  Female         40.000000                40.0              Female
4  35.0    Male         35.000000                35.0                Male
5   NaN  Female         32.142857                30.0              Female
6  28.0    Male         28.000000                28.0                Male
7  22.0    Male         22.000000                22.0                Male
8   NaN  Female         32.142857                30.0              Female
9  45.0     NaN         45.000000                45.0                Male

DataFrame with mean/median/mode imputation:
     age  age_mean_imputed  age_median_imputed  gender gender_mode_imputed
0  25.0         25.000000                25.0    Male                Male
1  30.0         30.000000                30.0  Female              Female
2   NaN         32.142857                30.0    Male                Male
3  40.0         40.000000                40.0  Female              Female
4  35.0         35.000000                35.0    Male                Male
5   NaN         32.142857                30.0  Female              Female
6  28.0         28.000000                28.0    Male                Male
7  22.0         22.000000                22.0    Male                Male
8   NaN         32.142857                30.0  Female              Female
9  45.0         45.000000                45.0     NaN                Male

Example with outlier:
Mean age with outlier: 51.666666666666664
Median age with outlier: 33.5

In [ ]:
type(df['age'])

pandas.core.series.Series

In [ ]:
# prompt: b) End of distribution imputation (min and max) with definition and example with the same age dataset we took before replace min and max value

import pandas as pd
import numpy as np

# Sample DataFrame with age data
data = {'age': [25, 30, 28, 40, 35, 60, 22, 45]}
df = pd.DataFrame(data)

# Calculate min and max age
min_age = df['age'].min()
max_age = df['age'].max()

# Create new columns with min-max imputation
df['age_min_imputed'] = df['age'].replace(max_age,min_age)
df['age_max_imputed'] = df['age'].replace(min_age,max_age)


print("Original DataFrame:\n", df)
print("\nDataFrame with min-max imputation:\n", df[['age', 'age_min_imputed', 'age_max_imputed']])

Original DataFrame:
    age  age_min_imputed  age_max_imputed
0   25               25               25
1   30               30               30
2   28               28               28
3   40               40               40
4   35               35               35
5   60               22               60
6   22               22               60
7   45               45               45

DataFrame with min-max imputation:
    age  age_min_imputed  age_max_imputed
0   25               25               25
1   30               30               30
2   28               28               28
3   40               40               40
4   35               35               35
5   60               22               60
6   22               22               60
7   45               45               45

In [ ]:
# prompt: c) Arbitrary value imputation with example and definition and take the same dataset of age and gender

import pandas as pd
import numpy as np

# Definition:
# Arbitrary value imputation replaces missing values with a pre-defined constant value.
# This method is simple but can introduce bias if the arbitrary value is not representative of the data.

# Example:
# Sample DataFrame with missing age and gender data
data = {'age': [25, 30, np.nan, 40, 35, np.nan, 28, 22, np.nan, 45],
        'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', np.nan]}
df = pd.DataFrame(data)

# Arbitrary value imputation for age (e.g., using -1)
df['age_arbitrary_imputed'] = df['age'].fillna(-1)


# Arbitrary value imputation for gender (e.g., using 'Unknown')
df['gender_arbitrary_imputed'] = df['gender'].fillna('Unknown')

print("Original DataFrame:\n", df)
print("\nDataFrame with arbitrary value imputation:\n", df[['age', 'age_arbitrary_imputed', 'gender', 'gender_arbitrary_imputed']])

Original DataFrame:
     age  gender  age_arbitrary_imputed gender_arbitrary_imputed
0  25.0    Male                   25.0                     Male
1  30.0  Female                   30.0                   Female
2   NaN    Male                   -1.0                     Male
3  40.0  Female                   40.0                   Female
4  35.0    Male                   35.0                     Male
5   NaN  Female                   -1.0                   Female
6  28.0    Male                   28.0                     Male
7  22.0    Male                   22.0                     Male
8   NaN  Female                   -1.0                   Female
9  45.0     NaN                   45.0                  Unknown

DataFrame with arbitrary value imputation:
     age  age_arbitrary_imputed  gender gender_arbitrary_imputed
0  25.0                   25.0    Male                     Male
1  30.0                   30.0  Female                   Female
2   NaN                   -1.0    Male                     Male
3  40.0                   40.0  Female                   Female
4  35.0                   35.0    Male                     Male
5   NaN                   -1.0  Female                   Female
6  28.0                   28.0    Male                     Male
7  22.0                   22.0    Male                     Male
8   NaN                   -1.0  Female                   Female
9  45.0                   45.0     NaN                  Unknown